version: '3.8'

services:
  # MySQL 8.0 数据库服务
  mysql:
    image: mysql:8.0
    container_name: permission-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: permission_system
      MYSQL_USER: permission
      MYSQL_PASSWORD: 123456
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./sql/nacos-init.sql:/docker-entrypoint-initdb.d/02-nacos-init.sql:ro
      - ./docker/mysql/conf.d:/etc/mysql/conf.d:ro
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - permission-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis 7.0 缓存服务
  redis:
    image: redis:7.0-alpine
    container_name: permission-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - permission-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nacos 2.2 注册中心和配置中心
  nacos:
    image: nacos/nacos-server:v2.2.3
    container_name: permission-nacos
    restart: always
    environment:
      MODE: standalone
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: nacos_config
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: 123456
      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      NACOS_AUTH_ENABLE: true
      NACOS_AUTH_TOKEN: SecretKey012345678901234567890123456789012345678901234567890123456789
      NACOS_AUTH_IDENTITY_KEY: serverIdentity
      NACOS_AUTH_IDENTITY_VALUE: security
      JVM_XMS: 256m
      JVM_XMX: 256m
      JVM_XMN: 128m
    ports:
      - "8848:8848"
      - "9848:9848"
    volumes:
      - nacos_logs:/home/nacos/logs
      - nacos_data:/home/nacos/data
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - permission-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8848/nacos/v1/console/health/readiness"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Nginx 反向代理（可选，需要时手动启用）
  # nginx:
  #   image: nginx:1.24-alpine
  #   container_name: permission-nginx
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     - nacos
  #   networks:
  #     - permission-network
  #   profiles:
  #     - nginx

# 数据卷定义
volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  nacos_logs:
    driver: local
  nacos_data:
    driver: local
  # nginx_logs:
  #   driver: local

# 网络定义
networks:
  permission-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16