# Gateway Service Configuration
server:
  port: 8080

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: dev
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
      config:
        server-addr: localhost:8848
        namespace: dev
        group: DEFAULT_GROUP
        file-extension: yml
        username: nacos
        password: nacos
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # 用户服务路由
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
            - name: AuthFilter
        # 权限服务路由
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
            - name: AuthFilter
        # 菜单服务路由
        - id: menu-service
          uri: lb://menu-service
          predicates:
            - Path=/api/menu/**
          filters:
            - StripPrefix=1
            - name: AuthFilter
        # 系统服务路由
        - id: system-service
          uri: lb://system-service
          predicates:
            - Path=/api/system/**
          filters:
            - StripPrefix=1
            - name: AuthFilter
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "GET,POST,PUT,DELETE,OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 5000ms
    connect-timeout: 5000ms
    lettuce:
      pool:
        max-active: 20
        max-wait: 3000ms
        max-idle: 10
        min-idle: 5
      shutdown-timeout: 100ms

logging:
  level:
    com.permission: debug
    org.springframework.cloud.gateway: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always