# User Service Configuration
server:
  port: 8081

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: dev
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
      config:
        server-addr: localhost:8848
        namespace: dev
        group: DEFAULT_GROUP
        file-extension: yml
        username: nacos
        password: nacos
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/permission_system?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    druid:
      # 连接池配置
      initial-size: 10
      min-idle: 10
      max-active: 50
      max-wait: 60000
      # 连接回收配置
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 900000
      # 连接检测配置
      validation-query: SELECT 1
      validation-query-timeout: 3
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 预编译语句配置
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 过滤器配置
      filters: stat,wall,slf4j
      # 连接属性配置
      connection-properties: >
        druid.stat.mergeSql=true;
        druid.stat.slowSqlMillis=2000;
        druid.wall.config.multiStatementAllow=true;
        druid.wall.config.noneBaseStatementAllow=true
      # 监控配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin123
        allow: 127.0.0.1
      # 连接泄漏检测
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true
  redis:
    host: localhost
    port: 6379
    password:
    database: 2
    timeout: 5000ms
    connect-timeout: 5000ms
    lettuce:
      pool:
        max-active: 20
        max-wait: 3000ms
        max-idle: 10
        min-idle: 5
      shutdown-timeout: 100ms
  cache:
    type: redis
    redis:
      time-to-live: 1800000  # 30分钟
      cache-null-values: false
      key-prefix: "user:"
      use-key-prefix: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.permission.user.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.permission: debug
    com.permission.user.mapper: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always